// Auto-generated from AssetList.txt with ./Assets/codegen.bat
#pragma once

enum AssetID {
    BG_PATTERN,
    BUTTON_1,
    BUTTON,
    BUTTON_ARROW_LEFT,
    BUTTON_ARROW_LEFT_OVERLAY_SHADOW,
    BUTTON_ARROW_RIGHT,
    BUTTON_ARROW_RIGHT_OVERLAY_SHADOW,
    CONNECTOR_BODY,
    CONNECTOR_CROSS_DOT,
    CONNECTOR_END,
    CONNECTOR_START,
    DRAG_IN_LIST_HOVER,
    SCALE_CONTROL,
    IC_ADD,
    IC_ARROW_BOTTOM,
    IC_ARROW_RATING_DECREASE,
    IC_ARROW_RATING_INCREASE,
    IC_ARROW_TOP,
    IC_COPY_16PX,
    IC_ERROR_16_PX,
    IC_HEATEDDS_SERVER_16_PX_1,
    IC_HEATEDDS_SERVER_16_PX,
    IC_HEATEDDS_SERVER_32_PX_1,
    IC_HEATEDDS_SERVER_32_PX,
    IC_HISTORY_16PX,
    IC_HYDRA_16_PX_1,
    IC_HYDRA_16_PX,
    IC_HYDRA_32_PX,
    IC_INFORMATION_16_PX,
    IC_INFORMATION_32_PX,
    IC_LOGS_16_PX,
    IC_PARTY_16_PX,
    IC_PROS_16_PX_1,
    IC_PROS_16_PX,
    IC_PROS_32_PX,
    IC_PVE_16_PX_1,
    IC_PVE_16_PX_2,
    IC_PVE_16_PX,
    IC_PVE_32_PX_1,
    IC_PVE_32_PX_2,
    IC_PVE_32_PX,
    IC_RUN,
    IC_SCALE_FIT_20_PX,
    IC_SCALE_MINUS_20_PX,
    IC_SCALE_PLUS_20_PX,
    IC_SCSESSION_16_PX,
    IC_STANDALONE_SERVER_16_PX_1,
    IC_STANDALONE_SERVER_16_PX,
    IC_STANDALONE_SERVER_32_PX,
    IC_USER_16_PX,
    IC_WARNING_16_PX,
    FOCUS_FRAME,
    PHYSICAL_24_PX_1,
    PHYSICAL_24_PX,
    PHYSICAL_56_PX_1,
    PHYSICAL_56_PX,
    VIRTUAL_24_PX_1,
    VIRTUAL_24_PX_2,
    VIRTUAL_24_PX_3,
    VIRTUAL_24_PX,
    VIRTUAL_56_PX_1,
    VIRTUAL_56_PX_2,
    VIRTUAL_56_PX_3,
    VIRTUAL_56_PX,
    LEADER,
    LOCAL,
    NETWORK_12_PX_1,
    NETWORK_12_PX,
    NETWORK_8_PX_1,
    NETWORK_8_PX,
    ASSET_COUNT
};

#ifdef COORD_ASSET_MAP_IMPL
static const char* AssetPaths[] = {
    "./Assets/bg_pattern.png",
    "./Assets/Button-1.png",
    "./Assets/Button.png",
    "./Assets/Button_arrow_left.png",
    "./Assets/Button_arrow_left_overlay_shadow.png",
    "./Assets/Button_arrow_right.png",
    "./Assets/Button_arrow_right_overlay_shadow.png",
    "./Assets/Connector_body.png",
    "./Assets/Connector_cross_dot.png",
    "./Assets/Connector_end.png",
    "./Assets/Connector_start.png",
    "./Assets/Drag in list hover.png",
    "./Assets/Scale control.png",
    "./Assets/Icons/ic_add.png",
    "./Assets/Icons/ic_arrow_bottom.png",
    "./Assets/Icons/ic_arrow_rating_decrease.png",
    "./Assets/Icons/ic_arrow_rating_increase.png",
    "./Assets/Icons/ic_arrow_top.png",
    "./Assets/Icons/ic_copy_16px.png",
    "./Assets/Icons/ic_error_16 px.png",
    "./Assets/Icons/ic_heatedds_server_16 px-1.png",
    "./Assets/Icons/ic_heatedds_server_16 px.png",
    "./Assets/Icons/ic_heatedds_server_32 px-1.png",
    "./Assets/Icons/ic_heatedds_server_32 px.png",
    "./Assets/Icons/ic_history_16px.png",
    "./Assets/Icons/ic_hydra_16 px-1.png",
    "./Assets/Icons/ic_hydra_16 px.png",
    "./Assets/Icons/ic_hydra_32 px.png",
    "./Assets/Icons/ic_information_16 px.png",
    "./Assets/Icons/ic_information_32 px.png",
    "./Assets/Icons/ic_logs_16 px.png",
    "./Assets/Icons/ic_party_16 px.png",
    "./Assets/Icons/ic_pros_16 px-1.png",
    "./Assets/Icons/ic_pros_16 px.png",
    "./Assets/Icons/ic_pros_32 px.png",
    "./Assets/Icons/ic_pve_16 px-1.png",
    "./Assets/Icons/ic_pve_16 px-2.png",
    "./Assets/Icons/ic_pve_16 px.png",
    "./Assets/Icons/ic_pve_32 px-1.png",
    "./Assets/Icons/ic_pve_32 px-2.png",
    "./Assets/Icons/ic_pve_32 px.png",
    "./Assets/Icons/ic_run.png",
    "./Assets/Icons/ic_scale_fit_20 px.png",
    "./Assets/Icons/ic_scale_minus_20 px.png",
    "./Assets/Icons/ic_scale_plus_20 px.png",
    "./Assets/Icons/ic_scsession_16 px.png",
    "./Assets/Icons/ic_standalone_server_16 px-1.png",
    "./Assets/Icons/ic_standalone_server_16 px.png",
    "./Assets/Icons/ic_standalone_server_32 px.png",
    "./Assets/Icons/ic_user_16 px.png",
    "./Assets/Icons/ic_warning_16 px.png",
    "./Assets/Module/Focus_frame.png",
    "./Assets/Module/Physical_24 px-1.png",
    "./Assets/Module/Physical_24 px.png",
    "./Assets/Module/Physical_56 px-1.png",
    "./Assets/Module/Physical_56 px.png",
    "./Assets/Module/Virtual_24 px-1.png",
    "./Assets/Module/Virtual_24 px-2.png",
    "./Assets/Module/Virtual_24 px-3.png",
    "./Assets/Module/Virtual_24 px.png",
    "./Assets/Module/Virtual_56 px-1.png",
    "./Assets/Module/Virtual_56 px-2.png",
    "./Assets/Module/Virtual_56 px-3.png",
    "./Assets/Module/Virtual_56 px.png",
    "./Assets/Status/Leader.png",
    "./Assets/Status/Local.png",
    "./Assets/Status/Network 12 px-1.png",
    "./Assets/Status/Network 12 px.png",
    "./Assets/Status/Network 8 px-1.png",
    "./Assets/Status/Network 8 px.png",
};
#endif // COORD_ASSET_MAP_IMPL
