// Auto-generated from AssetList.txt with ./Assets/codegen.bat
#pragma once

enum AssetID {
    HEATEDDS_DEVDSM_128PX,
    HEATEDDS_DEVDSM_24PX,
    HEATEDDS_DEVDSM_36PX,
    HEATEDDS_DEVDSM_56PX,
    HEATEDDS_DEVDSM_84PX,
    HYDRASAMPLE_128PX,
    HYDRASAMPLE_24PX,
    HYDRASAMPLE_36PX,
    HYDRASAMPLE_56PX,
    HYDRASAMPLE_84PX,
    MMFLOWSAMPLE_128PX,
    MMFLOWSAMPLE_24PX,
    MMFLOWSAMPLE_36PX,
    MMFLOWSAMPLE_56PX,
    MMFLOWSAMPLE_84PX,
    PROSSAMPLE_128PX,
    PROSSAMPLE_24PX,
    PROSSAMPLE_36PX,
    PROSSAMPLE_56PX,
    PROSSAMPLE_84PX,
    STANDALONE_128PX,
    STANDALONE_24PX,
    STANDALONE_36PX,
    STANDALONE_56PX,
    STANDALONE_84PX,
    INFORMATION_128PX,
    INFORMATION_24PX,
    INFORMATION_36PX,
    INFORMATION_56PX,
    INFORMATION_84PX,
    MMSESSION_128PX,
    MMSESSION_24PX,
    MMSESSION_36PX,
    MMSESSION_56PX,
    MMSESSION_84PX,
    PARTY_128PX,
    PARTY_24PX,
    PARTY_36PX,
    PARTY_56PX,
    PARTY_84PX,
    SCSESSION_128PX,
    SCSESSION_24PX,
    SCSESSION_36PX,
    SCSESSION_56PX,
    SCSESSION_84PX,
    USER_128PX,
    USER_24PX,
    USER_36PX,
    USER_56PX,
    USER_84PX,
    BG_PATTERN,
    BUTTON_1,
    BUTTON,
    BUTTON_ARROW_LEFT,
    BUTTON_ARROW_LEFT_OVERLAY_SHADOW,
    BUTTON_ARROW_RIGHT,
    BUTTON_ARROW_RIGHT_OVERLAY_SHADOW,
    CONNECTOR_BODY,
    CONNECTOR_CROSS_DOT,
    CONNECTOR_END,
    CONNECTOR_START,
    DRAG_IN_LIST_HOVER,
    SCALE_CONTROL,
    IC_ADD,
    IC_ARROW_BOTTOM,
    IC_ARROW_RATING_DECREASE,
    IC_ARROW_RATING_INCREASE,
    IC_ARROW_TOP,
    IC_COPY_16PX,
    IC_ERROR_16_PX,
    IC_HEATEDDS_SERVER_16_PX_1,
    IC_HEATEDDS_SERVER_16_PX,
    IC_HEATEDDS_SERVER_32_PX_1,
    IC_HEATEDDS_SERVER_32_PX,
    IC_HISTORY_16PX,
    IC_HYDRA_16_PX_1,
    IC_HYDRA_16_PX,
    IC_HYDRA_32_PX,
    IC_INFORMATION_16_PX,
    IC_INFORMATION_32_PX,
    IC_LOGS_16_PX,
    IC_PARTY_16_PX,
    IC_PROS_16_PX_1,
    IC_PROS_16_PX,
    IC_PROS_32_PX,
    IC_PVE_16_PX_1,
    IC_PVE_16_PX_2,
    IC_PVE_16_PX,
    IC_PVE_32_PX_1,
    IC_PVE_32_PX_2,
    IC_PVE_32_PX,
    IC_RUN,
    IC_SCALE_FIT_20_PX,
    IC_SCALE_MINUS_20_PX,
    IC_SCALE_PLUS_20_PX,
    IC_SCSESSION_16_PX,
    IC_STANDALONE_SERVER_16_PX_1,
    IC_STANDALONE_SERVER_16_PX,
    IC_STANDALONE_SERVER_32_PX,
    IC_USER_16_PX,
    IC_WARNING_16_PX,
    FOCUS_FRAME,
    PHYSICAL_24_PX_1,
    PHYSICAL_24_PX,
    PHYSICAL_56_PX_1,
    PHYSICAL_56_PX,
    VIRTUAL_24_PX_1,
    VIRTUAL_24_PX_2,
    VIRTUAL_24_PX_3,
    VIRTUAL_24_PX,
    VIRTUAL_56_PX_1,
    VIRTUAL_56_PX_2,
    VIRTUAL_56_PX_3,
    VIRTUAL_56_PX,
    LEADER,
    LOCAL,
    NETWORK_12_PX_1,
    NETWORK_12_PX,
    NETWORK_8_PX_1,
    NETWORK_8_PX,
    ASSET_COUNT
};

#ifdef COORD_ASSET_MAP_IMPL
static const char* AssetPaths[] = {
    "./Assets/Module/Physical/heatedDS_devDSM_128px.png",
    "./Assets/Module/Physical/heatedDS_devDSM_24px.png",
    "./Assets/Module/Physical/heatedDS_devDSM_36px.png",
    "./Assets/Module/Physical/heatedDS_devDSM_56px.png",
    "./Assets/Module/Physical/heatedDS_devDSM_84px.png",
    "./Assets/Module/Physical/hydraSample_128px.png",
    "./Assets/Module/Physical/hydraSample_24px.png",
    "./Assets/Module/Physical/hydraSample_36px.png",
    "./Assets/Module/Physical/hydraSample_56px.png",
    "./Assets/Module/Physical/hydraSample_84px.png",
    "./Assets/Module/Physical/mmFlowSample_128px.png",
    "./Assets/Module/Physical/mmFlowSample_24px.png",
    "./Assets/Module/Physical/mmFlowSample_36px.png",
    "./Assets/Module/Physical/mmFlowSample_56px.png",
    "./Assets/Module/Physical/mmFlowSample_84px.png",
    "./Assets/Module/Physical/prosSample_128px.png",
    "./Assets/Module/Physical/prosSample_24px.png",
    "./Assets/Module/Physical/prosSample_36px.png",
    "./Assets/Module/Physical/prosSample_56px.png",
    "./Assets/Module/Physical/prosSample_84px.png",
    "./Assets/Module/Physical/standAlone_128px.png",
    "./Assets/Module/Physical/standAlone_24px.png",
    "./Assets/Module/Physical/standAlone_36px.png",
    "./Assets/Module/Physical/standAlone_56px.png",
    "./Assets/Module/Physical/standAlone_84px.png",
    "./Assets/Module/Virtual/information_128px.png",
    "./Assets/Module/Virtual/information_24px.png",
    "./Assets/Module/Virtual/information_36px.png",
    "./Assets/Module/Virtual/information_56px.png",
    "./Assets/Module/Virtual/information_84px.png",
    "./Assets/Module/Virtual/mmSession_128px.png",
    "./Assets/Module/Virtual/mmSession_24px.png",
    "./Assets/Module/Virtual/mmSession_36px.png",
    "./Assets/Module/Virtual/mmSession_56px.png",
    "./Assets/Module/Virtual/mmSession_84px.png",
    "./Assets/Module/Virtual/party_128px.png",
    "./Assets/Module/Virtual/party_24px.png",
    "./Assets/Module/Virtual/party_36px.png",
    "./Assets/Module/Virtual/party_56px.png",
    "./Assets/Module/Virtual/party_84px.png",
    "./Assets/Module/Virtual/scSession_128px.png",
    "./Assets/Module/Virtual/scSession_24px.png",
    "./Assets/Module/Virtual/scSession_36px.png",
    "./Assets/Module/Virtual/scSession_56px.png",
    "./Assets/Module/Virtual/scSession_84px.png",
    "./Assets/Module/Virtual/user_128px.png",
    "./Assets/Module/Virtual/user_24px.png",
    "./Assets/Module/Virtual/user_36px.png",
    "./Assets/Module/Virtual/user_56px.png",
    "./Assets/Module/Virtual/user_84px.png",
    "./Assets/worn/bg_pattern.png",
    "./Assets/worn/Button-1.png",
    "./Assets/worn/Button.png",
    "./Assets/worn/Button_arrow_left.png",
    "./Assets/worn/Button_arrow_left_overlay_shadow.png",
    "./Assets/worn/Button_arrow_right.png",
    "./Assets/worn/Button_arrow_right_overlay_shadow.png",
    "./Assets/worn/Connector_body.png",
    "./Assets/worn/Connector_cross_dot.png",
    "./Assets/worn/Connector_end.png",
    "./Assets/worn/Connector_start.png",
    "./Assets/worn/Drag in list hover.png",
    "./Assets/worn/Scale control.png",
    "./Assets/worn/Icons/ic_add.png",
    "./Assets/worn/Icons/ic_arrow_bottom.png",
    "./Assets/worn/Icons/ic_arrow_rating_decrease.png",
    "./Assets/worn/Icons/ic_arrow_rating_increase.png",
    "./Assets/worn/Icons/ic_arrow_top.png",
    "./Assets/worn/Icons/ic_copy_16px.png",
    "./Assets/worn/Icons/ic_error_16 px.png",
    "./Assets/worn/Icons/ic_heatedds_server_16 px-1.png",
    "./Assets/worn/Icons/ic_heatedds_server_16 px.png",
    "./Assets/worn/Icons/ic_heatedds_server_32 px-1.png",
    "./Assets/worn/Icons/ic_heatedds_server_32 px.png",
    "./Assets/worn/Icons/ic_history_16px.png",
    "./Assets/worn/Icons/ic_hydra_16 px-1.png",
    "./Assets/worn/Icons/ic_hydra_16 px.png",
    "./Assets/worn/Icons/ic_hydra_32 px.png",
    "./Assets/worn/Icons/ic_information_16 px.png",
    "./Assets/worn/Icons/ic_information_32 px.png",
    "./Assets/worn/Icons/ic_logs_16 px.png",
    "./Assets/worn/Icons/ic_party_16 px.png",
    "./Assets/worn/Icons/ic_pros_16 px-1.png",
    "./Assets/worn/Icons/ic_pros_16 px.png",
    "./Assets/worn/Icons/ic_pros_32 px.png",
    "./Assets/worn/Icons/ic_pve_16 px-1.png",
    "./Assets/worn/Icons/ic_pve_16 px-2.png",
    "./Assets/worn/Icons/ic_pve_16 px.png",
    "./Assets/worn/Icons/ic_pve_32 px-1.png",
    "./Assets/worn/Icons/ic_pve_32 px-2.png",
    "./Assets/worn/Icons/ic_pve_32 px.png",
    "./Assets/worn/Icons/ic_run.png",
    "./Assets/worn/Icons/ic_scale_fit_20 px.png",
    "./Assets/worn/Icons/ic_scale_minus_20 px.png",
    "./Assets/worn/Icons/ic_scale_plus_20 px.png",
    "./Assets/worn/Icons/ic_scsession_16 px.png",
    "./Assets/worn/Icons/ic_standalone_server_16 px-1.png",
    "./Assets/worn/Icons/ic_standalone_server_16 px.png",
    "./Assets/worn/Icons/ic_standalone_server_32 px.png",
    "./Assets/worn/Icons/ic_user_16 px.png",
    "./Assets/worn/Icons/ic_warning_16 px.png",
    "./Assets/worn/Module/Focus_frame.png",
    "./Assets/worn/Module/Physical_24 px-1.png",
    "./Assets/worn/Module/Physical_24 px.png",
    "./Assets/worn/Module/Physical_56 px-1.png",
    "./Assets/worn/Module/Physical_56 px.png",
    "./Assets/worn/Module/Virtual_24 px-1.png",
    "./Assets/worn/Module/Virtual_24 px-2.png",
    "./Assets/worn/Module/Virtual_24 px-3.png",
    "./Assets/worn/Module/Virtual_24 px.png",
    "./Assets/worn/Module/Virtual_56 px-1.png",
    "./Assets/worn/Module/Virtual_56 px-2.png",
    "./Assets/worn/Module/Virtual_56 px-3.png",
    "./Assets/worn/Module/Virtual_56 px.png",
    "./Assets/worn/Status/Leader.png",
    "./Assets/worn/Status/Local.png",
    "./Assets/worn/Status/Network 12 px-1.png",
    "./Assets/worn/Status/Network 12 px.png",
    "./Assets/worn/Status/Network 8 px-1.png",
    "./Assets/worn/Status/Network 8 px.png",
};
#endif // COORD_ASSET_MAP_IMPL
